### ISSUE TITLE
请问是否支持remote方式shell模式下逐句调试?

### ISSUE THREAD

**Issue by appleyuchi** [alibaba/Alink#100]
①start-cluster.sh
②pyflink-shell.sh remote IP port
然后我就可以逐句调试了，

请问alink是否支持逐句调试？
官方例子都是local的

**Comment by appleyuchi** [comment]
https://github.com/alibaba/Alink/blob/master/pyalink/adult.ipynb

>>> from pyalink.alink import *

Use one of the following commands to start using PyAlink:
 - useLocalEnv(parallelism, flinkHome=None, config=None)
 - useRemoteEnv(host, port, parallelism, flinkHome=None, localIp="localhost", config=None)
Call resetEnv() to reset environment and switch to another.

>>> resetEnv()
>>> useLocalEnv(1, config=None)
Warning: cannot find pyflink path. If not running using 'flink run', please check if PyFlink is installed correctly.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/appleyuchi/anaconda3/envs/Python3.6/lib/python3.6/site-packages/pyalink/alink/env.py", line 126, in useLocalEnv
    j_configuration = _make_j_configuration(config, parallelism)
  File "/home/appleyuchi/anaconda3/envs/Python3.6/lib/python3.6/site-packages/pyalink/alink/env.py", line 33, in _make_j_configuration
    configuration = get_java_gateway().jvm.org.apache.flink.configuration.Configuration()
  File "/home/appleyuchi/anaconda3/envs/Python3.6/lib/python3.6/site-packages/pyalink/alink/py4j_util.py", line 28, in get_java_gateway
    _gateway = LocalJvmBridge.inst().gateway
  File "/home/appleyuchi/anaconda3/envs/Python3.6/lib/python3.6/site-packages/pyalink/alink/py4j_util.py", line 68, in inst
    cls._bridge.init()
  File "/home/appleyuchi/anaconda3/envs/Python3.6/lib/python3.6/site-packages/pyalink/alink/py4j_util.py", line 78, in init
    classpath=os.pathsep.join(list_all_jars())
  File "/home/appleyuchi/anaconda3/envs/Python3.6/lib/python3.6/site-packages/pyalink/alink/py4j_util.py", line 44, in list_all_jars
    os.listdir(os.path.join(flink_home, 'lib'))
  File "/home/appleyuchi/anaconda3/envs/Python3.6/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
