### ISSUE TITLE
flink1.11.1运行官方demo报错

### ISSUE THREAD

**Issue by lookhua** [alibaba/Alink#138]
操作步骤如下：
通过拷贝python下的java类库到flink/lib目录下
**-rw-r--r--. 1 root  root  16771919 Aug 12 15:03 alink_connector_all-1.2.0.jar
-rw-r--r--. 1 root  root  45496973 Aug 12 15:03 alink_core_flink-1.11_2.11-1.2.0.jar
-rw-r--r--. 1 root  root   6309265 Aug 12 15:03 alink_python-1.2.0-shaded.jar**
-rw-r--r--. 1 flink flink    90782 Jul 15 16:54 flink-csv-1.11.1.jar
-rw-r--r--. 1 flink flink    99462888 Jul 15 17:00 flink-dist_2.12-1.11.1.jar
-rw-r--r--. 1 flink flink   94865 Jul 15 16:54 flink-json-1.11.1.jar
-rw-r--r--. 1 flink flink  50 Jul 24 15:28 flink-s3-fs-hadoop.jar -> /opt/flink/opt/flink-metrics-prometheus-1.11.1.jar
-rw-r--r--. 1 flink flink  7712156 Jun 18 10:42 flink-shaded-zookeeper-3.4.14.jar
-rw-r--r--. 1 flink flink 34818659 Jul 15 16:59 flink-table-blink_2.12-1.11.1.jar
-rw-r--r--. 1 flink flink 31926004 Jul 15 16:58 flink-table_2.12-1.11.1.jar
-rw-r--r--. 1 flink flink    67114 Apr 20 20:47 log4j-1.2-api-2.12.1.jar
-rw-r--r--. 1 flink flink   276771 Apr 20 20:47 log4j-api-2.12.1.jar
-rw-r--r--. 1 flink flink  1674433 Apr 20 20:47 log4j-core-2.12.1.jar
-rw-r--r--. 1 flink flink    23518 Apr 20 20:47 log4j-slf4j-impl-2.12.1.jar

从git上获取alink项目，maven打包，上传demo的jar，flink通过界面运行程序
ui界面返回错误如下：
org.apache.flink.runtime.rest.handler.RestHandlerException: 
Could not execute application. at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$1(JarRunHandler.java:103) 
at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) 
at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) 
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) 
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at java.lang.Thread.run(Thread.java:748) 
Caused by: java.util.concurrent.CompletionException: org.apache.flink.util.FlinkRuntimeException: Could not execute application. 
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) 
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) 
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ... 
7 more Caused by: org.apache.flink.util.FlinkRuntimeException: Could not execute application. 
at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:81) 
at org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:67) 
at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$0(JarRunHandler.java:100) 
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ... 7 more Caused by: 
org.apache.flink.client.program.ProgramInvocationException: 
The main method caused an error: Cannot have more than one execute() or executeAsync() call in a single environment. 
at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:302) 
at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198) 
at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:149) 
at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:78) ... 10 more 
Caused by: org.apache.flink.util.FlinkRuntimeException: Cannot have more than one execute() or executeAsync() call in a single environment. 
at org.apache.flink.client.program.ContextEnvironment.validateAllowedExecution(ContextEnvironment.java:135) 
at org.apache.flink.client.program.ContextEnvironment.executeAsync(ContextEnvironment.java:123) 
at org.apache.flink.client.program.ContextEnvironment.execute(ContextEnvironment.java:72) 
at org.apache.flink.api.java.ExecutionEnvironment.execute(ExecutionEnvironment.java:873) 
at com.alibaba.alink.operator.batch.BatchOperator.collect(BatchOperator.java:571) 
at com.alibaba.alink.operator.batch.BatchOperator.triggerLazyEvaluation(BatchOperator.java:539) 
at com.alibaba.alink.operator.batch.BatchOperator.print(BatchOperator.java:351) 
at com.alibaba.alink.ALSExample.main(ALSExample.java:38) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:288) ... 13 more

**Comment by shaomengwang** [comment]
这个看起来是你的main函数中调用了两次execute

**Comment by JuiceZZ** [comment]
请问这个解决了吗？我现在也有同样的问题

**Comment by shaomengwang** [comment]
参考上边的回答，先关闭，有问题再具体问题看吧
