### ISSUE TITLE
Alink如何用Java连接MySQL？

### ISSUE THREAD

**Issue by MrGGGGGGG** [alibaba/Alink#161]
**我尝试用以下方式连接，但会报Could not find the mysql catelog factory.**
`String catalogName="mysql_test_catalog";
        String defaultDatabase="mall_mini";
        String mysqlVersion="8.0.20";
        String mysqlUrl="jdbc:mysql://localhost:3306/mall_mini";
        String port="3306";
        String userName="root";
        String password="root";
        String databaseName="mall_mini";  //数据库
        String objectName="customer_log";  //表名
        MySqlCatalog mySqlCatalog=new MySqlCatalog(catalogName,defaultDatabase,mysqlVersion,mysqlUrl,port,userName,password);
        HasCatalogObject.CatalogObject catalogObject=new HasCatalogObject.CatalogObject(mySqlCatalog, new ObjectPath(databaseName,objectName));
        CatalogSourceBatchOp catalogSourceBatchOp=new CatalogSourceBatchOp().setCatalogObject(catalogObject);
        catalogSourceBatchOp.print();//Could not find the mysql catelog factory.`

**以下为报错内容**
`Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Could not find the mysql catelog factory.
	at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAsThrowRuntime(ClassLoaderFactory.java:36)
	at com.alibaba.alink.common.io.catalog.MySqlCatalog.open(MySqlCatalog.java:77)
	at com.alibaba.alink.operator.batch.source.CatalogSourceBatchOp.initializeDataSource(CatalogSourceBatchOp.java:36)
	at com.alibaba.alink.operator.batch.source.BaseSourceBatchOp.getOutputTable(BaseSourceBatchOp.java:37)
	at com.alibaba.alink.operator.AlgoOperator.getSchema(AlgoOperator.java:195)
	at com.alibaba.alink.operator.batch.utils.MapBatchOp.linkFrom(MapBatchOp.java:37)
	... 9 more
	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Could not find the mysql catelog factory.
		at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAsThrowRuntime(ClassLoaderFactory.java:36)
		at com.alibaba.alink.common.io.catalog.MySqlCatalog.close(MySqlCatalog.java:82)
		at com.alibaba.alink.operator.batch.source.CatalogSourceBatchOp.initializeDataSource(CatalogSourceBatchOp.java:41)
		... 12 more
	Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not find the mysql catelog factory.
		at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAsThrowRuntime(ClassLoaderFactory.java:44)
		at com.alibaba.alink.common.io.catalog.MySqlCatalog.loadCatalog(MySqlCatalog.java:193)
		at com.alibaba.alink.common.io.catalog.MySqlCatalog.lambda$close$1(MySqlCatalog.java:82)
		at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.lambda$doAs$0(ClassLoaderFactory.java:27)
		at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAs(ClassLoaderFactory.java:53)
		at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAs(ClassLoaderFactory.java:26)
		at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAsThrowRuntime(ClassLoaderFactory.java:34)
		... 14 more
	Caused by: java.lang.RuntimeException: Could not find the mysql catelog factory.
		at com.alibaba.alink.common.io.catalog.MySqlCatalog.createCatalogFactory(MySqlCatalog.java:210)
		at com.alibaba.alink.common.io.catalog.MySqlCatalog.createCatalog(MySqlCatalog.java:217)
		at com.alibaba.alink.common.io.catalog.MySqlCatalog.lambda$loadCatalog$17(MySqlCatalog.java:194)
		at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAs(ClassLoaderFactory.java:53)
		at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAsThrowRuntime(ClassLoaderFactory.java:42)
		... 20 more
	Caused by: java.lang.ClassNotFoundException: com.alibaba.alink.common.io.catalog.mysql.factories.MySqlCatalogFactory
		at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
		at com.alibaba.alink.common.io.catalog.MySqlCatalog.createCatalogFactory(MySqlCatalog.java:204)
		... 24 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not find the mysql catelog factory.
	at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAsThrowRuntime(ClassLoaderFactory.java:44)
	at com.alibaba.alink.common.io.catalog.MySqlCatalog.loadCatalog(MySqlCatalog.java:193)
	at com.alibaba.alink.common.io.catalog.MySqlCatalog.lambda$open$0(MySqlCatalog.java:77)
	at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.lambda$doAs$0(ClassLoaderFactory.java:27)
	at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAs(ClassLoaderFactory.java:53)
	at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAs(ClassLoaderFactory.java:26)
	at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAsThrowRuntime(ClassLoaderFactory.java:34)
	... 14 more
Caused by: java.lang.RuntimeException: Could not find the mysql catelog factory.
	at com.alibaba.alink.common.io.catalog.MySqlCatalog.createCatalogFactory(MySqlCatalog.java:210)
	at com.alibaba.alink.common.io.catalog.MySqlCatalog.createCatalog(MySqlCatalog.java:217)
	at com.alibaba.alink.common.io.catalog.MySqlCatalog.lambda$loadCatalog$17(MySqlCatalog.java:194)
	at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAs(ClassLoaderFactory.java:53)
	at com.alibaba.alink.common.io.plugin.ClassLoaderFactory.doAsThrowRuntime(ClassLoaderFactory.java:42)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.alibaba.alink.common.io.catalog.mysql.factories.MySqlCatalogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.alibaba.alink.common.io.catalog.MySqlCatalog.createCatalogFactory(MySqlCatalog.java:204)
	... 24 more`

**我在源码中找到了报错的是createCatalogFactory方法中loadClass步骤**
`public static CatalogFactory createCatalogFactory(ClassLoader classLoader) {
		try {
			return (CatalogFactory) classLoader
				.loadClass("com.alibaba.alink.common.io.catalog.mysql.factories.MySqlCatalogFactory")
				.getConstructor()
				.newInstance();
		} catch (ClassNotFoundException | NoSuchMethodException
			| InstantiationException | IllegalAccessException | InvocationTargetException e) {
			throw new RuntimeException("Could not find the mysql catelog factory.", e);
		}
	}`

**请问如何解决，如何用Java连接MySQL？**

**Comment by shaomengwang** [comment]
download the plugin first.

ref: https://www.yuque.com/pinshu/alink_guide/czg4cx
