### ISSUE TITLE
Alink链接不上kafka，也无法sink。

### ISSUE THREAD

**Issue by 5917549999** [alibaba/Alink#169]
所用版本为Alink 1.3.2
Flink 1.12.2
python 3.7.4
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
脚本为：
from pyalink.alink import *
useLocalEnv(1, config=None)
URL = "http://alink-dataset.cn-hangzhou.oss.aliyun-inc.com/csv/iris.csv";
SCHEMA_STR = "sepal_length double, sepal_width double, petal_length double, petal_width double, category string";
data = CsvSourceStreamOp().setFilePath(URL).setSchemaStr(SCHEMA_STR)

sink = KafkaSinkStreamOp() \
    .setBootstrapServers("localhost:9092").setDataFormat("json") \
    .setTopic("iris")
sink.linkFrom(data)
StreamOperator.execute()
报错为：
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Traceback (most recent call last):
  File "/Users/yao/PycharmProjects/Alink/Alink_Kafka_Producer.py", line 28, in <module>
    sink.linkFrom(data)
  File "/Users/yao/.local/lib/python3.7/site-packages/pyalink/alink/stream/base.py", line 28, in linkFrom
    self._j_op.linkFrom(j_args)
  File "/Users/yao/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1154, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/yao/.local/lib/python3.7/site-packages/py4j/protocol.py", line 320, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o43.linkFrom.
: java.lang.RuntimeException: Not have parameter: pluginVersion
	at org.apache.flink.ml.api.misc.param.Params.lambda$getValue$3(Params.java:134)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:503)
	at org.apache.flink.ml.api.misc.param.Params.getValue(Params.java:131)
	at org.apache.flink.ml.api.misc.param.Params.get(Params.java:141)
	at com.alibaba.alink.operator.stream.sink.KafkaSinkStreamOp.sinkFrom(KafkaSinkStreamOp.java:30)
	at com.alibaba.alink.operator.stream.sink.KafkaSinkStreamOp.sinkFrom(KafkaSinkStreamOp.java:13)
	at com.alibaba.alink.operator.stream.sink.BaseSinkStreamOp.linkFrom(BaseSinkStreamOp.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
报错显示py4j.protocol.Py4JJavaError: An error occurred while calling o43.linkFrom.
: java.lang.RuntimeException: Not have parameter: pluginVersion
请问是因为什么，有什么解决办法吗

**Comment by 5917549999** [comment]
useLocalEnv(1, config=None)
URL = "http://alink-dataset.cn-hangzhou.oss.aliyun-inc.com/csv/iris.csv";
SCHEMA_STR = "sepal_length double, sepal_width double, petal_length double, petal_width double, category string";
data = CsvSourceStreamOp().setFilePath(URL).setSchemaStr(SCHEMA_STR)

sink = KafkaSinkStreamOp() \
    .setBootstrapServers("localhost:9092").setPluginVersion('0.11').setDataFormat("json") \
    .setTopic("iris")
sink.linkFrom(data)
StreamOperator.execute()
添加了.setPluginVersion('0.11')之后问题解决了
