### ISSUE TITLE
Are there any restrictions on the dataframeToOperator()?

### ISSUE THREAD

**Issue by dragonblare** [alibaba/Alink#180]
I'm new to Apache Flink and Alink, so please let me know if I'm saying anything wrong.

I'm currently doing research using Alink as part of my college thesis.
I'm trying to use a dataset and convert it using dataframeToOperator() with op_type="batch", and then apply it to a machine learning model. Then, if the number of features is more than a dozen, I get an error. However, if I reduce the number of features, the error is eliminated and the system works fine.
What is the cause of this symptom?

**Comment by Fanoid** [comment]
Hi, you may post your error log here.

Basically, `dataframeToOperator` use Flink `collect` Java API to collect data to the client memory in Java type of `List<Row>`, then convert it to pandas `DataFrame` with certain Java-Python type conversions. 

A common situation is the data is very large and exceeds some memory limits. In this case, the Java side crashes, and exceptions are thrown.

**Comment by dragonblare** [comment]
Thank you for your reply.

The following error message will be output.


```
Py4JJavaError: An error occurred while calling z:com.alibaba.alink.operator.batch.BatchOperator.execute.
: org.apache.flink.client.program.ProgramInvocationException: Job failed (JobID: 08a32671c6816a6c4d2b6f387b992518)
	at org.apache.flink.client.deployment.ClusterClientJobClientAdapter.lambda$null$6(ClusterClientJobClientAdapter.java:125)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$9(FutureUtils.java:394)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.apache.flink.client.program.rest.RestClusterClient.lambda$pollResourceAsync$24(RestClusterClient.java:670)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$9(FutureUtils.java:394)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
	at org.apache.flink.client.deployment.ClusterClientJobClientAdapter.lambda$null$6(ClusterClientJobClientAdapter.java:123)
	... 24 more
Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:216)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:206)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:197)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:682)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:79)
	at org.apache.flink.runtime.jobmaster.JobMaster$1.onMissingDeploymentsOf(JobMaster.java:238)
	at org.apache.flink.runtime.jobmaster.DefaultExecutionDeploymentReconciler.reconcileExecutionDeployments(DefaultExecutionDeploymentReconciler.java:61)
	at org.apache.flink.runtime.jobmaster.JobMaster$TaskManagerHeartbeatListener.reportPayload(JobMaster.java:1307)
	at org.apache.flink.runtime.jobmaster.JobMaster$TaskManagerHeartbeatListener.reportPayload(JobMaster.java:1288)
	at org.apache.flink.runtime.heartbeat.HeartbeatManagerImpl.receiveHeartbeat(HeartbeatManagerImpl.java:200)
	at org.apache.flink.runtime.jobmaster.JobMaster.heartbeatFromTaskManager(JobMaster.java:771)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:301)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.flink.util.FlinkException: Execution bca34bcbd2477cb5cc52f10999ff166a is unexpectedly no longer running on task executor 127.0.0.1:52681-b74f2a.
	at org.apache.flink.runtime.jobmaster.JobMaster$1.onMissingDeploymentsOf(JobMaster.java:243)
	... 31 more
```

I am also thinking that I may have exceeded the memory limit, but which part of the system can be improved to solve this problem?

**Comment by dragonblare** [comment]
>This means the flink job failed, and the reason is the client memory issue of List<Row> I mentioned before.
The job seemed failed in the TaskManager side.

I apologize for my lack of knowledge, but what can I do to solve the memory problem?

>Maybe you could start a standalone cluster, and submit the job to the cluster using useRemoteEnv, and then check the complete log.

I am currently working on a standalone cluster with **UseRemoteEnv** in jupyter notebook, how can I get it to output a complete log?

**Comment by Fanoid** [comment]
You can check logs in the Flink Web UI, usually can be accessed by localhost:8081. 
Both JobManager and TaskManger can provide some information in their logs.

**Comment by dragonblare** [comment]
We have a cluster of two computers, one running as a master and worker, and the other as a worker.
The logs for each are listed below.

[jobmanager_log.txt](https://github.com/alibaba/Alink/files/7109021/jobmanager_log.txt)
[taskmanager_10.0.1.23_61133-85de53_log.txt](https://github.com/alibaba/Alink/files/7109022/taskmanager_10.0.1.23_61133-85de53_log.txt)
[taskmanager_127.0.0.1_65223-cf0e7b_log.txt](https://github.com/alibaba/Alink/files/7109023/taskmanager_127.0.0.1_65223-cf0e7b_log.txt)

I would appreciate it if you could tell me if the attachment is wrong.
Thank you very much.

**Comment by Fanoid** [comment]
Hi, I found this in taskmanager_127.0.0.1_65223-cf0e7b_log.txt:

> 2021-09-04 10:27:23,472 DEBUG org.apache.flink.runtime.taskmanager.Task                    [] - Ensuring all FileSystem streams are closed for task DataSink (org.apache.flink.api.java.Utils$CollectHelper@7b24fd63) (1/1)#0 (30a948ff42cad70402fcd5b4c8f06443) [FINISHED]
2021-09-04 10:27:23,472 DEBUG org.apache.flink.runtime.taskmanager.Task                    [] - Ensuring all FileSystem streams are closed for task CHAIN DataSource (at initializeDataSource(MemSourceBatchOp.java:95) (org.apache.flink.api.java.io.CollectionInputFormat)) -> Map (Map at linkFrom(MapBatchOp.java:42)) (1/1)#0 (70e131a56c04f71a29b8d293c7672183) [FINISHED]
2021-09-04 10:27:23,473 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor           [] - Un-registering task and sending final execution state FINISHED to JobManager for task DataSink (org.apache.flink.api.java.Utils$CollectHelper@7b24fd63) (1/1)#0 30a948ff42cad70402fcd5b4c8f06443.
2021-09-04 10:27:23,580 WARN  org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler      [] - Could not create remote rpc invocation message. Failing rpc invocation because...
java.io.IOException: The rpc invocation size 10540269 exceeds the maximum akka framesize.
	at org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.createRpcInvocationMessage(AkkaInvocationHandler.java:282) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.invokeRpc(AkkaInvocationHandler.java:209) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.invoke(AkkaInvocationHandler.java:132) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at org.apache.flink.runtime.rpc.akka.FencedAkkaInvocationHandler.invoke(FencedAkkaInvocationHandler.java:88) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at com.sun.proxy.$Proxy25.updateTaskExecutionState(Unknown Source) ~[?:?]

This seems to indicate that the job has finished, but the results were not sent back to JobManager successfully due to "The rpc invocation size 10540269 exceeds the maximum akka framesize".
You may increase `akka.framesize` to a larger value, like `1048576000b`. 

A more detailed description can be found here: [https://ci.apache.org/projects/flink/flink-docs-master/docs/deployment/config/#akka-framesize](url)

**Comment by dragonblare** [comment]
I was able to get dataframeToOperator working successfully!
Thank you so much for your kind help!
