### ISSUE TITLE
关于文本相似度的例子TextSimilarityPairwiseBatchOpTest 运行问题

### ISSUE THREAD

**Issue by tanchy82** [alibaba/Alink#189]
来源语雀  Alink1.5.1文档-->批组件-->相似度-->文本两两相似度计算demo，运行错误

public class TextSimilarityPairwiseBatchOpTest {
	@Test
	public void testTextSimilarityPairwiseBatchOp() throws Exception {
		List <Row> df = Arrays.asList(
			Row.of(0, "a b c d e", "a a b c e"),
			Row.of(1, "a a c e d w", "a a b b e d"),
			Row.of(2, "c d e f a", "b b c e f a"),
			Row.of(3, "b d e f h", "d d e a c"),
			Row.of(4, "a c e d m", "a e e f b c")
		);
		BatchOperator <?> inOp1 = new MemSourceBatchOp(df, "id int, text1 string, text2 string");
		StreamOperator <?> inOp2 = new MemSourceStreamOp(df, "id int, text1 string, text2 string");
		BatchOperator <?> batchOp = new TextSimilarityPairwiseBatchOp().setSelectedCols("text1", "text2").setMetric(
			"LEVENSHTEIN").setOutputCol("output");
		batchOp.linkFrom(inOp1).print();
		StreamOperator <?> streamOp = new TextSimilarityPairwiseStreamOp().setSelectedCols("text1", "text2").setMetric(
			"COSINE").setOutputCol("output");
		streamOp.linkFrom(inOp2).print();
		StreamOperator.execute();
	}
}
error:
Exception in thread "main" java.lang.RuntimeException: org.apache.flink.table.api.ExpressionParserException: Could not parse expression at column 4: ',' expected but 'i' found
id int,text1 string,text2 string
   ^
	at com.alibaba.alink.operator.batch.utils.MapBatchOp.linkFrom(MapBatchOp.java:53)
	at com.alibaba.alink.operator.batch.utils.MapBatchOp.linkFrom(MapBatchOp.java:22)
	at com.oldtan.TextCompare.main(TextCompare.java:33)
Caused by: org.apache.flink.table.api.ExpressionParserException: Could not parse expression at column 4: ',' expected but 'i' found
id int,text1 string,text2 string
   ^

**Comment by aohaiMhs** [comment]
我的本地跑没问题，可以加群说一下详细情况。

**Comment by tanchy82** [comment]
哦。谢谢，我再测试下。因为之前测试异常，用scala写了个simhash算法处理了当前需求。
