### ISSUE TITLE
StratifiedSampleBatchOp执行空指针问题

### ISSUE THREAD

**Issue by dongshengl** [alibaba/Alink#194]
您好，使用StratifiedSampleBatchOp组件做采样时，如下设置，在执行时报空指针
new StratifiedSampleBatchOp() .setStrataRatios("0:0.05,1:1.0")

异常信息如下：
java.lang.NullPointerException: 0 is not contained in map!
	at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:76) ~[flink-core-1.12.3.jar:1.12.3]
	at com.alibaba.alink.operator.batch.dataproc.StratifiedSampleBatchOp$StratifiedSampleReduce.reduce(StratifiedSampleBatchOp.java:87) 

打断点发现fractionMap在put时，key是String，但是get时是Object，并不一致，导致获取的fraction为null，请问如何设置才能正确获取数据？
![image](https://user-images.githubusercontent.com/20124107/150907671-5c4715f0-d2e9-49df-84be-8a9c49998b16.png)

**Comment by Fanoid** [comment]
看起来是数据中这一列是整型，不是字符串类型，导致 key 查不到。

**Comment by xuyang1706** [comment]
问题已经修复，在下个版本中发布
