### ISSUE TITLE
Throws below error when i tried to submit Flink job to session cluster. any help would be appreciated

### ISSUE THREAD

**Issue by vidya72** [alibaba/Alink#195]
Server Response:
org.apache.flink.runtime.rest.handler.RestHandlerException: Could not execute application. at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$1(JarRunHandler.java:103) at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.util.concurrent.CompletionException: org.apache.flink.util.FlinkRuntimeException: Could not execute application. at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ... 7 more Caused by: org.apache.flink.util.FlinkRuntimeException: Could not execute application. at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:81) at org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:67) at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$0(JarRunHandler.java:100) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ... 7 more Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: No configuration setting found for key 'silvertail' at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:302) at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198) at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:149) at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:78) ... 10 more Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'silvertail' at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156) at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149) at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176) at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188) at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193) at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250) at com.cdo.fraud.ReadSSL$SilvertailJob.inputTopic(ReadSSL.scala:36) at com.cdo.fraud.ReadSSL$SilvertailJob.inputTopic$(ReadSSL.scala:36) at com.cdo.fraud.ReadAndPrint.inputTopic(ReadAndPrint.scala:12) at com.cdo.fraud.ReadSSL$SilvertailStringJob.dataSource(ReadSSL.scala:103) at com.cdo.fraud.ReadSSL$SilvertailStringJob.dataSource$(ReadSSL.scala:103) at com.cdo.fraud.ReadAndPrint.dataSource$lzycompute(ReadAndPrint.scala:12) at com.cdo.fraud.ReadAndPrint.dataSource(ReadAndPrint.scala:12) at com.att.cdosec.flinkutils.common.FlinkJob.run(FlinkJob.scala:83) at com.cdo.fraud.Job$.main(Job.scala:42) at com.cdo.fraud.Job.main(Job.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:288) ... 13 more

**Comment by Fanoid** [comment]
It seems the root cause is 

> Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'silvertail'

And from the last several lines, it seems the exception comes from `com.cdo.fraud.Job.main`.
