### ISSUE TITLE
使用JsonValue读取json属性出现NoSuchMethodError异常

### ISSUE THREAD

**Issue by ONI-MIKO** [alibaba/Alink#224]
**开发环境**
1. open jdk1.8.0_345
2. Windows 11
3. IntelliJ IDEA 2022.2.2
4. alink1.6.0+flink1.13

看了下没有其他com.jayway.jsonpath的依赖，尝试把alink_core_flink依赖的排除后可以预期抛出ClassNotFund异常，手动引用依赖仍然会出现NoSuchMethodError异常。idea调试时断点打在JsonPathMapper.115行，手动执行JsonPath.read(json, jsonPaths[i])可以正常得到返回结果，放开断点继续运行会出现NoSuchMethodError

异常信息
```java
Caused by: java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.read(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
	at com.alibaba.alink.common.utils.JsonPathMapper.map(JsonPathMapper.java:115)
	at com.alibaba.alink.common.mapper.Mapper.bufferMap(Mapper.java:154)
	at com.alibaba.alink.common.mapper.MapperChain.map(MapperChain.java:84)
	at com.alibaba.alink.common.mapper.ComboModelMapper.map(ComboModelMapper.java:54)
	at com.alibaba.alink.common.mapper.ModelMapperAdapter.map(ModelMapperAdapter.java:45)
	at com.alibaba.alink.common.mapper.ModelMapperAdapter.map(ModelMapperAdapter.java:18)
	at org.apache.flink.runtime.operators.MapDriver.run(MapDriver.java:103)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:514)
	at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:357)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:776)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
	at java.lang.Thread.run(Thread.java:750)
Disconnected from the target VM, address: '127.0.0.1:60181', transport: 'socket'

Process finished with exit code 1

```

测试部分代码
```java
Pipeline pipeline = new Pipeline(
    new JsonValue()
            .setJsonPath("$[*].code", "$[*].score")
            .setSelectedCol("profiles")
            .setOutputCols("codes", "scores")
            .setOutputColTypes("OBJECT_ARRAY<STRING>", "OBJECT_ARRAY<DOUBLE>")
);

```

pom依赖
```xml
         <properties>
		<java.version>1.8</java.version>
		<alink.version>1.6.0</alink.version>
		<alink.flink.major.version>1.13</alink.flink.major.version>
		<alink.scala.major.version>2.11</alink.scala.major.version>
		<flink.version>1.13.0</flink.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<!-- https://mvnrepository.com/artifact/cn.hutool/hutool-all -->
		<dependency>
			<groupId>cn.hutool</groupId>
			<artifactId>hutool-core</artifactId>
			<version>5.8.9</version>
		</dependency>

		<dependency>
			<groupId>com.alibaba.alink</groupId>
			<artifactId>alink_core_flink-${alink.flink.major.version}_${alink.scala.major.version}</artifactId>
			<version>${alink.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
<!--				<exclusion>-->
<!--					<groupId>com.jayway.jsonpath</groupId>-->
<!--					<artifactId>json-path</artifactId>-->
<!--				</exclusion>-->
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-streaming-scala_${alink.scala.major.version}</artifactId>
			<version>${flink.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-table-planner_${alink.scala.major.version}</artifactId>
			<version>${flink.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-clients_${alink.scala.major.version}</artifactId>
			<version>${flink.version}</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>com.jayway.jsonpath</groupId>-->
<!--			<artifactId>json-path</artifactId>-->
<!--			<version>2.7.0</version>-->
<!--		</dependency>-->
	</dependencies>
```

**Comment by ONI-MIKO** [comment]
alnk core编译时用到的jsonpath版本为0.5.6，score为compile，所以需要手动引入0.5.6版本的json-path包解决此问题
<dependency>
	<groupId>com.jayway.jsonpath</groupId>
	<artifactId>json-path</artifactId>
	<version>0.5.6</version>
</dependency>
