### ISSUE TITLE
LinearSvm error:Labels count should be 2 in in linear classification algo.

### ISSUE THREAD

**Issue by shaohongzhu** [alibaba/Alink#226]

**Comment by shaohongzhu** [comment]
Caused by: ERROR: 0x0860080000001006-Illegal state: Labels count should be 2 in in linear classification algo.
	at com.alibaba.alink.common.exceptions.AkPreconditions.checkState(AkPreconditions.java:174)
	at com.alibaba.alink.operator.common.linear.BaseLinearModelTrainBatchOp$3.flatMap(BaseLinearModelTrainBatchOp.java:186)
	at com.alibaba.alink.operator.common.linear.BaseLinearModelTrainBatchOp$3.flatMap(BaseLinearModelTrainBatchOp.java:178)
	at org.apache.flink.runtime.operators.FlatMapDriver.run(FlatMapDriver.java:113)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:519)
	at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:360)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)

**Comment by shaohongzhu** [comment]
Labels 值的问题
