### ISSUE TITLE
本地可运行的alink脚本上传至flink服务器后会出现报错

### ISSUE THREAD

**Issue by 2635215324** [alibaba/Alink#234]
在本地可以运行的alink例子脚本，打包上传至flink服务器后会出现

> org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Unable to instantiate java compiler
>         at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
>         at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
>         at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
>         at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
>         at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
>         at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
>         at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
>         at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
>         at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
> Caused by: java.lang.IllegalStateException: Unable to instantiate java compiler
>         at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:428)
>         at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.load3(JaninoRelMetadataProvider.java:374)
>         at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.lambda$static$0(JaninoRelMetadataProvider.java:109)
>         at org.apache.flink.calcite.shaded.com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
>         at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
>         at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
>         at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
>         at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
>         at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache.get(LocalCache.java:3951)
>         at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
>         at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
>         at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.create(JaninoRelMetadataProvider.java:469)
>         at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.revise(JaninoRelMetadataProvider.java:481)
>         at org.apache.calcite.rel.metadata.RelMetadataQueryBase.revise(RelMetadataQueryBase.java:95)
>         at org.apache.calcite.rel.metadata.RelMetadataQuery.getPulledUpPredicates(RelMetadataQuery.java:784)
>         at org.apache.calcite.rel.rules.ReduceExpressionsRule$ProjectReduceExpressionsRule.onMatch(ReduceExpressionsRule.java:303)
>         at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:333)
>         at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:542)
>         at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:407)
>         at org.apache.calcite.plan.hep.HepPlanner.executeInstruction(HepPlanner.java:243)
>         at org.apache.calcite.plan.hep.HepInstruction$RuleInstance.execute(HepInstruction.java:127)
>         at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:202)
>         at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:189)
>         at org.apache.flink.table.planner.plan.optimize.program.FlinkHepProgram.optimize(FlinkHepProgram.scala:69)
>         at org.apache.flink.table.planner.plan.optimize.program.FlinkHepRuleSetProgram.optimize(FlinkHepRuleSetProgram.scala:87)
>         at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram.$anonfun$optimize$1(FlinkChainedProgram.scala:62)
>         at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:156)
>         at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:156)
>         at scala.collection.Iterator.foreach(Iterator.scala:937)
>         at scala.collection.Iterator.foreach$(Iterator.scala:937)
>         at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
>         at scala.collection.IterableLike.foreach(IterableLike.scala:70)
>         at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
>         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
>         at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:156)
>         at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:154)
>         at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
>         at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram.optimize(FlinkChainedProgram.scala:58)
>         at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.optimizeTree(StreamCommonSubGraphBasedOptimizer.scala:161)
>         at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.doOptimize(StreamCommonSubGraphBasedOptimizer.scala:79)
>         at org.apache.flink.table.planner.plan.optimize.CommonSubGraphBasedOptimizer.optimize(CommonSubGraphBasedOptimizer.scala:77)
>         at org.apache.flink.table.planner.delegation.PlannerBase.optimize(PlannerBase.scala:300)
>         at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:183)
>         at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1665)
>         at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeQueryOperation(TableEnvironmentImpl.java:805)
>         at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1274)
>         at org.apache.flink.table.api.internal.TableImpl.execute(TableImpl.java:601)
>         at org.example.App.main(App.java:57)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
>         ... 8 more
> Caused by: java.lang.ClassCastException: org.codehaus.janino.CompilerFactory cannot be cast to org.codehaus.commons.compiler.ICompilerFactory
>         at org.codehaus.commons.compiler.CompilerFactoryFactory.getCompilerFactory(CompilerFactoryFactory.java:129)
>         at org.codehaus.commons.compiler.CompilerFactoryFactory.getDefaultCompilerFactory(CompilerFactoryFactory.java:79)
>         at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:426)
>         ... 60 more
我检查了我的依赖，确定没有关于Janino版本的冲突，请问我应该怎么解决这个问题呢？
我使用的是flink1.13.2 Scala2.11

**Comment by ltcaxx** [comment]
解决了吗。我也遇到了这个问题

**Comment by ieayoio** [comment]
官方的例子都跑不通，很难受啊，`pip install pyalink`在python3.8环境就装不上(已经配了镜像源)，跑示例就报这个

**Comment by ieayoio** [comment]
> 官方的例子都跑不通，很难受啊，`pip install pyalink`在python3.8环境就装不上(已经配了镜像源)，跑示例就报这个

pyalink还是装不上，但是java示例跑通了，在配置文件里加`classloader.resolve-order: parent-first`就好了，官方的例子中写着添加`<scope>provided</scope>`应该也能解决

**Comment by ieayoio** [comment]
> 官方的例子都跑不通，很难受啊，`pip install pyalink`在python3.8环境就装不上(已经配了镜像源)，跑示例就报这个
我不明白，为什么在安装pyalink过程中会把组件安装很多相同的版本，镜像源代理都安装不上
![image](https://github.com/alibaba/Alink/assets/7099604/817f142f-ba4a-4be9-9524-fe41d9e41d1b)

**Comment by ieayoio** [comment]
> 官方的例子都跑不通，很难受啊，`pip install pyalink`在python3.8环境就装不上(已经配了镜像源)，跑示例就报这个

报错了，这次时这个错误，之前还有不一样的错误
```
ERROR: Exception:
Traceback (most recent call last):
  File "/root/miniconda3/envs/alink/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/root/miniconda3/envs/alink/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/root/miniconda3/envs/alink/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/root/miniconda3/envs/alink/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/root/miniconda3/envs/alink/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/miniconda3/envs/alink/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
```

![image](https://github.com/alibaba/Alink/assets/7099604/c7aed781-ea63-4fa2-8825-ac6c8bb52327)
