### ISSUE TITLE
ALSExample发生错误

### ISSUE THREAD

**Issue by 0xqq** [alibaba/Alink#33]
打包官网example上传到flink上跑ALSExample出现以下错误

2019-12-27 14:56:29
java.lang.Exception: The user defined 'open()' method caused an exception: null
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:499)
	at org.apache.flink.runtime.iterative.task.AbstractIterativeTask.run(AbstractIterativeTask.java:157)
	at org.apache.flink.runtime.iterative.task.IterationIntermediateTask.run(IterationIntermediateTask.java:107)
	at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:369)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NegativeArraySizeException
	at com.alibaba.alink.operator.common.recommendation.AlsTrain$9.open(AlsTrain.java:308)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.api.java.operators.translation.WrappingFunction.open(WrappingFunction.java:45)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:495)
	... 6 more

**Comment by cloud2010** [comment]
我是jdk 8， centos环境，也是同样的问题
