### ISSUE TITLE
Kafka as the sink, something was wrong.

### ISSUE THREAD

**Issue by xixici** [alibaba/Alink#43]
When I test the kafka as the sink, something was wrong.
The codes are as follows:
```
public class writeKafka {
    private static void write() throws Exception {
        String URL = "data/iris.csv";
        String SCHEMA_STR
                = "sepal_length double, sepal_width double, petal_length double, petal_width double, category string";
        CsvSourceStreamOp data = new CsvSourceStreamOp().setFilePath(URL).setSchemaStr(SCHEMA_STR);
        Kafka011SinkStreamOp sink = new Kafka011SinkStreamOp()
                .setBootstrapServers("127.0.0.1:9092")
                .setDataFormat("json")
                .setTopic("iris");

        data.link(sink);

        StreamOperator.execute();
    }

    public static void main(String[] args) throws Exception {
        write();

    }
}
```
It goes wrong like
```
09:54:15,518 WARN  org.apache.kafka.common.utils.AppInfoParser                   - Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=kafka_011_-6885371916521496791
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:58)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:335)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:191)
	at com.alibaba.alink.operator.common.io.kafka.KafkaBaseOutputFormat.getKafkaProducer(KafkaBaseOutputFormat.java:160)
	at com.alibaba.alink.operator.common.io.kafka.KafkaBaseOutputFormat.open(KafkaBaseOutputFormat.java:166)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.open(OutputFormatSinkFunction.java:65)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:529)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:393)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
```

I don't know what caused it. Besides, I found that the message was generated normally.

**Comment by chengscu** [comment]
Is there another producer generating message to the same topic?  In our next release, we will fix this problem by allowing users to specify unique client.id.
