### ISSUE TITLE
在Fllink中窗口事件中整合Alink算法时（Standalone）集群Job运行失败。

### ISSUE THREAD

**Issue by czs1993** [alibaba/Alink#78]
环境：Centos 7
java jdk:1.8
Flink：1.10

使用大致代码：
消费指定Topic-->对消费数据进行 KeyBy-->定义 滑动窗口-->在窗口中利用 Pipline 进行数据预测。

```

import com.alibaba.alink.operator.batch.BatchOperator;
import com.alibaba.alink.operator.batch.source.CsvSourceBatchOp;
import com.alibaba.alink.pipeline.LocalPredictor;
import com.alibaba.alink.pipeline.PipelineModel;
import metricModelPredict.dto.*;
import metricModelPredict.schema.ApmMetricMetaDeserializationSchema;
import org.apache.flink.api.common.functions.MapFunction;
import org.apache.flink.api.common.state.ValueState;
import org.apache.flink.api.common.state.ValueStateDescriptor;
import org.apache.flink.api.common.typeinfo.TypeHint;
import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.api.java.tuple.Tuple;
import org.apache.flink.configuration.Configuration;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.streaming.api.functions.windowing.ProcessWindowFunction;
import org.apache.flink.streaming.api.windowing.assigners.TumblingProcessingTimeWindows;
import org.apache.flink.streaming.api.windowing.time.Time;
import org.apache.flink.streaming.api.windowing.windows.TimeWindow;
import org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumer011;
import org.apache.flink.types.Row;
import org.apache.flink.util.Collector;

import java.util.Properties;

public class MetricPredictJob {
    public static void main(String[] args) throws Exception
    {
        final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        //kafka consumer
        Properties properties = new Properties();
        properties.setProperty("bootstrap.servers", "192.168.1.10:9092");// kafka 地址
        properties.setProperty("group.id", "Metric_Predict");// consumer group
        FlinkKafkaConsumer011<ApmMetricSourcePerSecond> consumer = new FlinkKafkaConsumer011<>(
                "APM_Metrics",//指标源数据topic
                new ApmMetricMetaDeserializationSchema(),
                properties);
        DataStream<ApmMetricValue> inputStream=env.addSource(consumer).map(new MapFunction<ApmMetricSourcePerSecond, ApmMetricValue>() {
            @Override
            public ApmMetricValue map(ApmMetricSourcePerSecond inputValue) throws Exception {
                    return new ApmMetricValue(inputValue.MetricHashValue, inputValue.MetricValue, inputValue.Timestamp);
            }
        });

       DataStream<AlertMetric> outputStream = inputStream
                .keyBy("MetricHashValue") //根据指标Hash值进行分流。
                .window(TumblingProcessingTimeWindows.of(Time.seconds(10)))//定义滚动窗口为10s进行指标预测计算
                .process(new ProcessWindowFunction<ApmMetricValue, AlertMetric, Tuple, TimeWindow>() {

                    private transient ValueState<PipelineModel> metricModelState;//存储模型State
                    @Override
                    public void open(Configuration parameters) throws Exception {
                        super.open(parameters);
                        //定义存储模型数据的State
                        ValueStateDescriptor<PipelineModel> descriptor = new ValueStateDescriptor<PipelineModel>("modelfile",
                                TypeInformation.of(new TypeHint<PipelineModel>() {}) );
                        metricModelState = getRuntimeContext().getState(descriptor);
                    }
                    @Override
                    public void process(Tuple tuple, Context context,
                                        Iterable<ApmMetricValue> iterable,
                                        Collector<AlertMetric> collector) throws Exception {
                        String metricHashValue=tuple.getField(0);
                        PipelineModel metricModel=metricModelState.value();
                        if(metricModel==null)//当模型为空时，从指定地址拉取模型文件
                        {
                            String modelPath= String.format("http://192.168.1.12:8888/model/%s_model.csv", metricHashValue);
                            BatchOperator modelFile=new CsvSourceBatchOp(modelPath, PipelineModel.PIPELINE_MODEL_SCHEMA);
                            //加载模型文件， 集群中部署Job时运行到这里加载失败，然后导致
                            metricModel=PipelineModel.load(modelFile);
                            metricModelState.update(metricModel);//将获取的模型更新到State中。
                        }
                        //对指标进行实时预测
                        LocalPredictor localPredictor = metricModel.getLocalPredictor("Timestamp long");
                        for (ApmMetricValue item:iterable) {
                            Long featureLabel = item.Timestamp;
                            Row row = Row.of(featureLabel);//基于时戳进行 指标值预测。
                            Row predictValue = localPredictor.map(row);
                            Double predValue = Double.valueOf(predictValue.getField(1).toString());
                            if(Math.abs(predValue-item.MetricValue)/item.MetricValue>0.2)//判断预测值与实际值偏移比
                            {
                                //当做异常指标输出。
                               collector.collect(new AlertMetric(item.MetricHashValue,item.MetricValue,predValue,item.Timestamp));
                            }
                        }
                    }
                });
        outputStream.print();
        env.execute();
    }
}

```
问题：
在本地可运行但是单个指标处理时内存消耗非常大达到 3G.
将Job上传到 Flink集群中，运行时，一到 PipelineModel.load(modelFile)时，
standalonesession和taskexecutor  日志都含以下错误信息：
Flink 集群 taskmanager.memory.network.min 配置大小为 512m

```

java.lang.OutOfMemoryError: Could not allocate enough memory segments for NetworkBufferPool (required (Mb): 192, allocated (Mb): 124, missing (Mb): 68). Cause: Direct buffer memory
	at org.apache.flink.runtime.io.network.buffer.NetworkBufferPool.<init>(NetworkBufferPool.java:138)
	at org.apache.flink.runtime.io.network.NettyShuffleServiceFactory.createNettyShuffleEnvironment(NettyShuffleServiceFactory.java:96)
	at org.apache.flink.runtime.io.network.NettyShuffleServiceFactory.createShuffleEnvironment(NettyShuffleServiceFactory.java:64)
	at org.apache.flink.runtime.io.network.NettyShuffleServiceFactory.createShuffleEnvironment(NettyShuffleServiceFactory.java:47)
	at org.apache.flink.runtime.taskexecutor.TaskManagerServices.createShuffleEnvironment(TaskManagerServices.java:313)
	at org.apache.flink.runtime.taskexecutor.TaskManagerServices.fromConfiguration(TaskManagerServices.java:228)
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.startTaskManager(TaskManagerRunner.java:372)
	at org.apache.flink.runtime.minicluster.MiniCluster.startTaskExecutor(MiniCluster.java:513)
	at org.apache.flink.runtime.minicluster.MiniCluster.startTaskManagers(MiniCluster.java:504)
	at org.apache.flink.runtime.minicluster.MiniCluster.start(MiniCluster.java:310)
	at org.apache.flink.client.deployment.executors.LocalExecutor.startMiniCluster(LocalExecutor.java:117)
	at org.apache.flink.client.deployment.executors.LocalExecutor.execute(LocalExecutor.java:63)
	at org.apache.flink.api.java.ExecutionEnvironment.executeAsync(ExecutionEnvironment.java:944)
	at org.apache.flink.api.java.ExecutionEnvironment.execute(ExecutionEnvironment.java:860)
	at org.apache.flink.api.java.ExecutionEnvironment.execute(ExecutionEnvironment.java:844)
	at org.apache.flink.api.java.DataSet.collect(DataSet.java:413)
	at com.alibaba.alink.operator.batch.BatchOperator.collect(BatchOperator.java:276)
	at com.alibaba.alink.pipeline.ModelExporterUtils.unpackTransformersArray(ModelExporterUtils.java:91)
	at com.alibaba.alink.pipeline.PipelineModel.load(PipelineModel.java:149)
	at com.alibaba.alink.pipeline.PipelineModel.load(PipelineModel.java:142)
	at metricModelPredict.job.ModelPredictProcess.process(ModelPredictProcess.java:200)
	at metricModelPredict.job.ModelPredictProcess.process(ModelPredictProcess.java:45)
	at org.apache.flink.streaming.runtime.operators.windowing.functions.InternalIterableProcessWindowFunction.process(InternalIterableProcessWindowFunction.java:50)
	at org.apache.flink.streaming.runtime.operators.windowing.functions.InternalIterableProcessWindowFunction.process(InternalIterableProcessWindowFunction.java:32)
	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.emitWindowContents(WindowOperator.java:549)
	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.onEventTime(WindowOperator.java:457)
	at org.apache.flink.streaming.api.operators.InternalTimerServiceImpl.advanceWatermark(InternalTimerServiceImpl.java:276)
	at org.apache.flink.streaming.api.operators.InternalTimeServiceManager.advanceWatermark(InternalTimeServiceManager.java:128)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.processWatermark(AbstractStreamOperator.java:787)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitWatermark(OneInputStreamTask.java:181)
	at org.apache.flink.streaming.runtime.streamstatus.StatusWatermarkValve.findAndOutputNewMinWatermarkAcrossAlignedChannels(StatusWatermarkValve.java:179)
	at org.apache.flink.streaming.runtime.streamstatus.StatusWatermarkValve.inputWatermark(StatusWatermarkValve.java:101)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:153)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:128)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:69)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:311)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:187)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:487)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:470)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:707)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:532)
	at java.lang.Thread.run(Thread.java:748)
```

Alink中基于流的算法应用是不是不可以嵌入Flink的一些窗口事件中？，如果可以是不是缺少了什么环境配置的地方？Alink的Pipeline中是否包含了Flink一样的 keyby、Map、以及其他的算子？后续能否提供一些Java API的使用样例。
 请大佬抽空解疑。

**Comment by shaomengwang** [comment]
从文件加载LocalPredictor即可

https://github.com/alibaba/Alink/blob/1cf674982861fe7b33145e80f66d92d863af0dc5/core/src/main/java/com/alibaba/alink/pipeline/LocalPredictor.java#L33
